In [19]:
df = pd.read_csv(
    r"D:\Celebal internship\Sample_Superstore.csv",
    encoding="latin1"
)

In [18]:
import pandas as pd
import sqlite3

In [8]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [20]:
df.shape

(9994, 21)

In [21]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [23]:
conn = sqlite3.connect("superstore.db")
cursor = conn.cursor()

In [24]:
df.to_sql(
    "superstore_raw",
    conn,
    if_exists="replace",
    index=False
)

9994

In [25]:
pd.read_sql(
    "SELECT * FROM superstore_raw LIMIT 5",
    conn
)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [16]:
cursor.execute("""
CREATE TABLE customers AS
SELECT DISTINCT
    [Customer ID] AS customer_id,
    [Customer Name] AS customer_name
FROM superstore_raw
""")

conn.commit()

OperationalError: table customers already exists

In [15]:
cursor.execute("""
CREATE TABLE orders AS
SELECT DISTINCT
    [Order ID] AS order_id,
    [Customer ID] AS customer_id,
    [Order Date] AS order_date,
    Sales
FROM superstore_raw
""")

conn.commit()

In [16]:
cursor.execute("""
CREATE TABLE products AS
SELECT DISTINCT
    [Product ID] AS product_id,
    [Product Name] AS product_name,
    Category
FROM superstore_raw
""")

conn.commit()

In [17]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
""", conn)

             name
0  superstore_raw
1       customers
2          orders
3        products

In [18]:
#Orders Above Average Sales (Subquery)
query = """
SELECT *
FROM orders
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM orders
)
"""

pd.read_sql(query, conn)

            order_id customer_id  order_date      Sales
0     CA-2016-152156    CG-12520   11/8/2016   261.9600
1     CA-2016-152156    CG-12520   11/8/2016   731.9400
2     US-2015-108966    SO-20335  10/11/2015   957.5775
3     CA-2014-115812    BH-11710    6/9/2014   907.1520
4     CA-2014-115812    BH-11710    6/9/2014  1706.1840
...              ...         ...         ...        ...
2354  US-2016-103674    AP-10720   12/6/2016   271.9600
2355  US-2016-103674    AP-10720   12/6/2016   249.5840
2356  US-2016-103674    AP-10720   12/6/2016   437.4720
2357  CA-2017-121258    DB-13060   2/26/2017   258.5760
2358  CA-2017-119914    CC-12220    5/4/2017   243.1600

[2359 rows x 4 columns]

In [19]:
#Highest Order Per Customer
query = """
SELECT *
FROM orders o
WHERE Sales =
(
    SELECT MAX(o2.Sales)
    FROM orders o2
    WHERE o.customer_id = o2.customer_id
)
"""

pd.read_sql(query, conn)

           order_id customer_id  order_date      Sales
0    CA-2016-152156    CG-12520   11/8/2016   731.9400
1    US-2015-108966    SO-20335  10/11/2015   957.5775
2    CA-2014-115812    BH-11710    6/9/2014  1706.1840
3    CA-2015-106320    EB-13870   9/25/2015  1044.6300
4    US-2015-150630    TB-21520   9/17/2015  3083.4300
..              ...         ...         ...        ...
790  CA-2015-159534    DH-13075   3/20/2015  1087.9360
791  CA-2016-129630    IM-15055    9/4/2016  2799.9600
792  CA-2017-121559    HW-14935    6/1/2017  2405.2000
793  CA-2017-153871    RB-19435  12/11/2017   735.9800
794  US-2016-103674    AP-10720   12/6/2016   437.4720

[795 rows x 4 columns]

In [20]:
#Total Sales Per Customer (CTE)
query = """
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM customer_sales
"""

pd.read_sql(query, conn)

    customer_id  total_sales
0      AA-10315     5563.560
1      AA-10375     1056.390
2      AA-10480     1790.512
3      AA-10645     5086.935
4      AB-10015      886.156
..          ...          ...
788    XP-21865     2374.658
789    YC-21895     5454.350
790    YS-21880     6720.444
791    ZC-21910     8025.707
792    ZD-21925     1493.944

[793 rows x 2 columns]

In [21]:
#Customers Above Average Sales
query = """
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM customer_sales
WHERE total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
)
"""

pd.read_sql(query, conn)

    customer_id  total_sales
0      AA-10315     5563.560
1      AA-10645     5086.935
2      AB-10060     7755.620
3      AB-10105    14473.571
4      AC-10450     5527.846
..          ...          ...
289    VW-21775     6134.038
290    WB-21850     6160.102
291    YC-21895     5454.350
292    YS-21880     6720.444
293    ZC-21910     8025.707

[294 rows x 2 columns]

In [22]:
#Rank Customers by Sales
query = """
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(Sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_sales,
    RANK() OVER
    (
        ORDER BY total_sales DESC
    ) AS sales_rank
FROM customer_sales
"""

pd.read_sql(query, conn)

    customer_id  total_sales  sales_rank
0      SM-20320    25043.050           1
1      TC-20980    19052.218           2
2      RB-19360    15117.339           3
3      TA-21385    14595.620           4
4      AB-10105    14473.571           5
..          ...          ...         ...
788    RS-19870       22.328         789
789    MG-18205       16.739         790
790    CJ-11875       16.520         791
791    LD-16855        5.304         792
792    TS-21085        4.833         793

[793 rows x 3 columns]

In [23]:
#ROW_NUMBER()
query = """
SELECT
    customer_id,
    order_id,
    Sales,

ROW_NUMBER() OVER
(
PARTITION BY customer_id
ORDER BY Sales DESC
) AS row_num

FROM orders
"""

pd.read_sql(query, conn)

     customer_id        order_id     Sales  row_num
0       AA-10315  CA-2016-103982  3930.072        1
1       AA-10315  CA-2014-128055   673.568        2
2       AA-10315  CA-2016-103982   431.976        3
3       AA-10315  CA-2017-147039   362.940        4
4       AA-10315  CA-2014-128055    52.980        5
...          ...             ...       ...      ...
9987    ZD-21925  CA-2017-141481    61.440        5
9988    ZD-21925  CA-2014-143336    22.720        6
9989    ZD-21925  US-2016-147991    16.720        7
9990    ZD-21925  CA-2016-152471    15.984        8
9991    ZD-21925  CA-2014-143336     8.560        9

[9992 rows x 4 columns]

In [24]:
#Top 5 Customers
query = """
WITH customer_sales AS
(
SELECT
customer_id,
SUM(Sales) AS total_sales
FROM orders
GROUP BY customer_id
)

SELECT *
FROM customer_sales
ORDER BY total_sales DESC
LIMIT 5
"""

pd.read_sql(query, conn)

  customer_id  total_sales
0    SM-20320    25043.050
1    TC-20980    19052.218
2    RB-19360    15117.339
3    TA-21385    14595.620
4    AB-10105    14473.571

In [25]:
#Lowest 5 Customers
query = """
WITH customer_sales AS
(
SELECT
customer_id,
SUM(Sales) AS total_sales
FROM orders
GROUP BY customer_id
)

SELECT *
FROM customer_sales
ORDER BY total_sales
LIMIT 5
"""

pd.read_sql(query, conn)

  customer_id  total_sales
0    TS-21085        4.833
1    LD-16855        5.304
2    CJ-11875       16.520
3    MG-18205       16.739
4    RS-19870       22.328

In [26]:
#Single Order Customers
query = """
SELECT
customer_id,
COUNT(*) AS order_count
FROM orders
GROUP BY customer_id
HAVING COUNT(*) = 1
"""

pd.read_sql(query, conn)

  customer_id  order_count
0    AO-10810            1
1    CJ-11875            1
2    JR-15700            1
3    LD-16855            1
4    RE-19405            1

In [26]:
#Highest Order Value Per Customer
query = """
SELECT
customer_id,
MAX(Sales) AS highest_order
FROM orders
GROUP BY customer_id
"""

pd.read_sql(query, conn)

    customer_id  highest_order
0      AA-10315       3930.072
1      AA-10375        499.980
2      AA-10480        479.970
3      AA-10645       1323.900
4      AB-10015        341.960
..          ...            ...
788    XP-21865        337.088
789    YC-21895       2934.330
790    YS-21880       2793.528
791    ZC-21910       1516.200
792    ZD-21925        823.960

[793 rows x 2 columns]

In [27]:
#JOIN + CTE + WINDOW FUNCTION
query = """
WITH customer_sales AS
(
SELECT
customer_id,
SUM(Sales) AS total_sales
FROM orders
GROUP BY customer_id
)

SELECT
c.customer_name,
cs.total_sales,

RANK() OVER
(
ORDER BY cs.total_sales DESC
) AS customer_rank

FROM customer_sales cs

JOIN customers c
ON cs.customer_id = c.customer_id

ORDER BY customer_rank
"""

pd.read_sql(query, conn)

       customer_name  total_sales  customer_rank
0        Sean Miller    25043.050              1
1       Tamara Chand    19052.218              2
2       Raymond Buch    15117.339              3
3       Tom Ashbrook    14595.620              4
4      Adrian Barton    14473.571              5
..               ...          ...            ...
788       Roy Skaria       22.328            789
789  Mitch Gastineau       16.739            790
790     Carl Jackson       16.520            791
791     Lela Donovan        5.304            792
792    Thais Sissman        4.833            793

[793 rows x 3 columns]